# Gohan setup is generated by Instacart tooling and should stay local.
# The guard makes this a no-op on a Bento box without gohan installed.
[ -f "$HOME/.config/gohan/gohan.sh" ] && source "$HOME/.config/gohan/gohan.sh"
