# Instacart laptop zsh configuration
# Sources shared config and adds work-machine hooks

# macOS-specific plugin must be set before sourcing shared config.
DEVICE_PLUGINS=(macos)

source ~/.zshrc.common

# Gohan setup is generated by Instacart tooling and should stay local.
[ -f "$HOME/.config/gohan/gohan.sh" ] && source "$HOME/.config/gohan/gohan.sh"

# Instacart setup owns this profile; keep its generated contents local.
[ -f "$HOME/.instacart_shell_profile" ] && source "$HOME/.instacart_shell_profile"
